# See https://github.com/geerlingguy/ansible-collection-mac/tree/master/roles/dock
dockitems_remove:
  - Launchpad
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - TV
  - Music
  - Podcasts
  - News
  - 'App Store'

dockitems_persist:
  - name: Safari
    path: /Applications/Safari.app
    pos: 1
  - name: System Preferences
    path: /System/Applications/System%20Preferences.app
    pos: 2
  - name: Google Chrome
    path: /Applications/Google%20Chrome.app
    pos: 3
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 4
  - name: Visual Studio Code
    path: /Applications/Visual%20Studio%20Code.app
    pos: 5
  - name: Spotify
    path: /Applications/Spotify.app
    pos: 6
  - name: Discord
    path: /Applications/Discord.app
    pos: 7
  - name: Signal
    path: /Applications/Signal.app
    pos: 8
  - name: Slack
    path: /Applications/Slack.app
    pos: 9

# See https://github.com/geerlingguy/ansible-collection-mac/tree/master/roles/homebrew
homebrew_installed_packages:
  - act
  - age
  - ansible
  - ansible-lint
  - automake
  - avrdude
  - awscli
  - bash-completion
  - bat
  - btop
  - bun
  - caddy
  - cloc
  - cmake
  - coreutils
  - curl
  - deno
  - direnv
  - dog
  - exiftool
  - ffmpeg
  - flyctl
  - gcc
  - git
  - git-delta
  - git-lfs
  - gnuplot
  - htop
  - httpie
  - jq
  - just
  - languagetool
  - maven
  - middleclick
  - mitmproxy
  - nano
  - neofetch
  - netcat
  - nim
  - nmap
  - node
  - node@16
  - openjdk
  - pixi
  - podman
  - postgresql
  - pstree
  - qrencode
  - rattler-build
  - ripgrep
  - ripgrep-all
  - ruby
  - rust
  - sqlite
  - tmux
  - tree
  - typst
  - vim
  - wget
  - xz
  - yq
  - yt-dlp
  - zig
  - zsh

homebrew_taps:
  - artginzburg/tap
  - oven-sh/bun

homebrew_cask_apps:
  - anki
  - discord
  - docker
  - firefox
  - google-chrome
  - hiddenbar
  - iina
  - inkscape
  - insomnia
  - iterm2
  - karabiner-elements
  - linearmouse
  - michaelvillar-timer
  - notion
  - obs
  - obsidian
  - orbstack
  - raycast
  - rectangle
  - shottr
  - signal
  - slack
  - spotify
  - telegram
  - tunnelblick
  - ukelele
  - visual-studio-code

npm_packages:
  - serve
  - pnpm
  - yarn
  - npm
  - nodemon

vscode_extensions:
  - aaron-bond.better-comments # highlights comments matching certain patterns (todo, fixme, etc.)
  - bibhasdn.unique-lines # removes duplicate lines from selection (command)
  - biomejs.biome
  - bradlc.vscode-tailwindcss # some small tailwind support
  - charliermarsh.ruff
  - Compulim.vscode-clock # clock in status bar
  - Dart-Code.dart-code
  - Dart-Code.flutter
  - dbaeumer.vscode-eslint
  - EditorConfig.EditorConfig
  - fallenwood.vimL
  - ftsamoyed.theme-pink-cat-boo
  - GitHub.copilot
  - github.vscode-github-actions
  - github.vscode-pull-request-github
  - jnbt.vscode-rufo
  - jock.svg
  - kamikillerto.vscode-colorize # colorize hex codes
  - keyring.Lua
  - kosz78.nim
  - ltex-plus.vscode-ltex-plus
  - max-SS.Cyberpunk@1.2.13
  - mbessey.vscode-rufo
  - mgwg.light-pink-theme
  - mikestead.dotenv
  - ms-azuretools.vscode-docker
  - ms-python.debugpy
  - ms-python.mypy-type-checker
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-python.vscode-python-envs
  - ms-vscode.atom-keybindings
  - ms-vscode.cpptools
  - ms-vsliveshare.vsliveshare
  - mvllow.rose-pine
  - myriad-dreamin.tinymist
  - Orta.vscode-twoslash-queries # display typescript types with "// ^?"
  - rebornix.toggle
  - redhat.java
  - redhat.vscode-yaml
  - sashaweiss.block-travel
  - shd101wyy.markdown-preview-enhanced
  - shengchen.vscode-checkstyle
  - slevesque.vscode-hexdump
  - tamasfe.even-better-toml
  - tomoki1207.pdf
  - unifiedjs.vscode-mdx@1.2.5
  - vadimcn.vscode-lldb
  - Vallentin.vscode-bnf
  - vscjava.vscode-java-debug
  - vscjava.vscode-java-test
  - webfreak.cute-theme
  - wmaurer.change-case # switch selection between camelCase, snake_case, etc.
  - yoavbls.pretty-ts-errors
  - Yummygum.city-lights-icon-vsc
  - yummygum.city-lights-theme

ohmyzsh_plugins:
  - { name: git }
  - { name: fzf-zsh-plugin, repo: https://github.com/unixorn/fzf-zsh-plugin.git }
  - { name: zsh-completions, repo: https://github.com/zsh-users/zsh-completions.git }
  - { name: zsh-syntax-highlighting, repo: https://github.com/zsh-users/zsh-syntax-highlighting.git }

config_folder:
  - bat
  - vscode
  - git
  - iTerm2
  - karabiner
  - neofetch
  - sqlite3
  - tmux
# - vim
  - linearmouse
